### ISSUE TITLE
Install-Module with Source will fail each time

### ISSUE THREAD

**Issue by tek0011** [hbuckle/puppet-powershellmodule#1]
using source param will fail each time, as that is passed to the install block:

```
  def install_command
    command = "Install-Module #{@resource[:name]} -Force"
    command << " -RequiredVersion #{@resource[:ensure]}" unless [:present, :latest].include? @resource[:ensure]
    command << " -Source #{@resource[:source]}" if @resource[:source]
    command
  end
```
is going to call `-Source` each time and will fail each time since `-Source` is not a valid parameter for `Install-Module`

should set with -Repository after having user set the -Repository name via `psrepository`

https://docs.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershell-5.1

**Comment by hbuckle** [comment]
Thanks for the report, will get this updated with the correct parameter
