### ISSUE TITLE
Lowercased SourceLocation 

### ISSUE THREAD

**Issue by MassimoSporchia** [hbuckle/puppet-powershellmodule#11]
Hello,

is there a particular reason to have the SourceLocation lowercased?

In particular in these two situations:

https://github.com/hbuckle/puppet-powershellmodule/blob/a91a6d4f378e6c7ad8bc4dfc0f817ee59509c8f1/lib/puppet/type/psrepository.rb#L30

and 

https://github.com/hbuckle/puppet-powershellmodule/blob/a91a6d4f378e6c7ad8bc4dfc0f817ee59509c8f1/lib/puppet/provider/psrepository/powershellcore.rb#L73

Since I think most of the webserver out there doesn't rewrite urls (e.g. Nexus Sonatype doesn't do it), I was wondering if removing these parameter alteration would be a thing.

**Comment by hbuckle** [comment]
Hi - this is just an internal thing to make it easier to compare strings. Although URLs aren't case sensitive, Puppet is so if the casing were different Puppet would think it needed to be changed. It should have no effect on actually interacting with repos.

**Comment by MassimoSporchia** [comment]
It does affect the interaction with repos, this code for example doesn't work with the lowercase:
`
psrepository { 'PSGalleryProxy':
    ensure              => present,
    source_location     => 'http://mylocalnexus/repository/PowerShellGallery_proxy/',
    installation_policy => 'untrusted',
    provider            => 'windowspowershell',
  }
`

Since a call to "http://mylocalnexus/repository/PowerShellGallery_proxy/" returns 200, a call to "http://mylocalnexus/repository/powershellgallery_proxy/" returns 404 hence the Set-PSRepository command returns malformed URL

**Comment by hbuckle** [comment]
Ah ok, I didn't know that some servers treated the URL as case sensitive. I should be able to update this to remove the lower casing.

**Comment by MassimoSporchia** [comment]
I've got minimal modification in my current workspace, if you want I'll make a pull request :)

**Comment by hbuckle** [comment]
2.0.0 makes source location case sensitive
