### ISSUE TITLE
cannot set version for windowspowershell provider

### ISSUE THREAD

**Issue by spali** [hbuckle/puppet-powershellmodule#12]
Module version: 1.0.0
OS: Windows 2016 1607 (Build: 14393.2312)
Powershell Version: 5.1.14393.2312
Ruby: ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
Puppet: 5.3.3

```puppet
  psrepository { 'PSGallery':
    ensure              => present,
    source_location     => 'https://www.powershellgallery.com/api/v2/',
    installation_policy => 'trusted',
    provider            => 'windowspowershell',
  }

  package { 'PSWindowsUpdate':
    ensure   => '2.0.0.4',
    source   => 'PSGallery',
    provider => 'windowspowershell',
  }
```
produces:
```puppet
Error: Failed to apply catalog: Parameter ensure failed on Package[PSWindowsUpdate]: Provider windowspowershell must have features 'versionable' to set 'ensure' to '2.0.4' at /etc/puppetlabs/code/environments/production/site/profile/manifests/windows/update/install.pp:11
```
If i use `latest`, it works.

Don't know much about ruby and creating custom providers, but if I'm not wrong, you are inheriting the provider `windowspowershell` from the `powershellcore` which has versionable as feature defined.
Seems not to be inherited?

**Comment by rsteenwyk** [comment]
I can replicate the same issue, I'm not sure how to fix it but this would definitely enhance the module a ton to get this working.

**Comment by hbuckle** [comment]
2.0.0 sets :versionable on the windowspowershell provider
