### ISSUE TITLE
Some dsc modules are created every time during the apply

### ISSUE THREAD

**Issue by wmaniek123** [hbuckle/puppet-powershellmodule#17]
Notice: **/Stage[main]/Main/Package[**NetworkingDSC]**/ensure:** created
Notice: **/Stage[main]/Main/Package[ComputerManagementDSC]/ensure:** created
Notice: **/Stage[main]/Main/Package[CertificateDSC]/ensure:** created

Debug:

Debug: Executing: 'C:/Windows/System32/WindowsPowerShell/v1.0/powershell.EXE -NoProfile -ExecutionPolicy Bypass -NonInteractive -NoLogo -Command $ProgressPreference = 'SilentlyContinue'; $ErrorActionPreference = 'Stop';     @(Get-PackageProvider).foreach({
      [ordered]@{
        'name' = $_.Name.ToLower()
        'version' = $_.Version.ToString()
      } | ConvertTo-Json -Depth 99 -Compress
    })
'
Debug: Prefetching windowspowershell resources for package
Debug: Executing: 'C:/Windows/System32/WindowsPowerShell/v1.0/powershell.EXE -NoProfile -ExecutionPolicy Bypass -NonInteractive -NoLogo -Command $ProgressPreference = 'SilentlyContinue'; $ErrorActionPreference = 'Stop';     Get-Package -AllVersions -ProviderName PowerShellGet -Scope AllUsers -Type Module |
    Group-Object -Property Name | % {
      [ordered]@{
        'name' = $_.Name
        'ensure' = @(($_.Group).Version)
        'provider' = 'windowspowershell'
      } | ConvertTo-Json -Depth 99 -Compress
    }
'
Debug: Executing: 'C:/Windows/System32/WindowsPowerShell/v1.0/powershell.EXE -NoProfile -ExecutionPolicy Bypass -NonInteractive -NoLogo -Command $ProgressPreference = 'SilentlyContinue'; $ErrorActionPreference = 'Stop'; Install-Module NetworkingDSC -Scope AllUsers -Force -Repository PSGallery'
Notice: /Stage[main]/Main/Package[NetworkingDSC]/ensure: created
Debug: /Package[NetworkingDSC]: The container Class[Main] will propagate my refresh event
Debug: Executing: 'C:/Windows/System32/WindowsPowerShell/v1.0/powershell.EXE -NoProfile -ExecutionPolicy Bypass -NonInteractive -NoLogo -Command $ProgressPreference = 'SilentlyContinue'; $ErrorActionPreference = 'Stop'; Install-Module ComputerManagementDSC -Scope AllUsers -Force -Repository PSGallery'
Notice: /Stage[main]/Main/Package[ComputerManagementDSC]/ensure: created
Debug: /Package[ComputerManagementDSC]: The container Class[Main] will propagate my refresh event
Debug: Executing: 'C:/Windows/System32/WindowsPowerShell/v1.0/powershell.EXE -NoProfile -ExecutionPolicy Bypass -NonInteractive -NoLogo -Command $ProgressPreference = 'SilentlyContinue'; $ErrorActionPreference = 'Stop'; Install-Module CertificateDSC -Scope AllUsers -Force -Repository PSGallery'
Notice: /Stage[main]/Main/Package[CertificateDSC]/ensure: created

Funny part is that other packages are not created everytime 

package { 'SecurityPolicyDsc':
  ensure   => latest,
  provider => 'windowspowershell',
  source   => 'PSGallery',
}->

get-package -allversions -providername powershellget -scope allusers -type Module | group-object -property name | % { [ordered]@{'name'=$_.name;'ensure'=@(($_.Group).version);'provider'='windowspowershell'} | ConvertTo-Json -Depth 99 -Compress }

{"name":"CertificateDsc","ensure":["4.2.0.0"],"provider":"windowspowershell"}
{"name":"ComputerManagementDsc","ensure":["5.2.0.0"],"provider":"windowspowershell"}
{"name":"NetworkingDsc","ensure":["6.1.0.0"],"provider":"windowspowershell"}
{"name":"SecurityPolicyDsc","ensure":["2.5.0.0"],"provider":"windowspowershell"}
{"name":"xActiveDirectory","ensure":["2.21.0.0"],"provider":"windowspowershell"}
{"name":"xPendingReboot","ensure":["0.4.0.0"],"provider":"windowspowershell"}

**Comment by hbuckle** [comment]
I think this is down to case sensitivity - could you check that the package name in the puppet manifest matches the name of the module in the powershell gallery exactly - so `NetworkingDsc` instead of `NetworkingDSC`

**Comment by wmaniek123** [comment]
Thanks that made the trick! Thanks for quick reply!
