### ISSUE TITLE
provider windowspowershell must be versionable

### ISSUE THREAD

**Issue by MassimoSporchia** [hbuckle/puppet-powershellmodule#18]
Hello,

I might be missing something but I'm getting the following error:

> Error: Failed to apply catalog: Parameter ensure failed on Package[StorageDsc]: Provider windowspowershell must have features 'versionable' to set 'ensure' to '4.1.0'

The code I'm using is the following:
```
package { 'StorageDsc':
    ensure   => '4.1.0',
    source   => 'PSGalleryProxy',
    provider => 'windowspowershell',
  }
```
Using this works:
```
package { 'StorageDsc':
    ensure   => present,
    source   => 'PSGalleryProxy',
    provider => 'windowspowershell',
  }
```

From the README.md this seems to be possible, though.
```
package { 'nameOfInternallyDevelopedModule':
  ensure   => '1.0.5',
  source   => 'my-internal-repo',
  provider => 'windowspowershell',
}
```

Am I missing something?

**Comment by hbuckle** [comment]
Hi - sorry for the late reply, github failed to notify me when the issue was raised.
Versioning should work - the windowspowershell provider has the versionable feature enabled - can you confirm which version of the module you are using - versionable was added in 2.0.0

**Comment by MassimoSporchia** [comment]
Heh, sorry for my delay now, @hbuckle .
I was using version 1.0.0. 
I guess case is solved!
